server:
  replicaCount: 1
  config:
    persistence:
      default:
        driver: "sql"
        sql:
          driver: "postgres"
          host: temporal-postgresql
          port: 5432
          database: temporal
          user: postgres
          password: temporal123
          maxConns: 20
          maxConnLifetime: "1h"
      visibility:
        driver: "sql"
        sql:
          driver: "postgres"
          host: temporal-postgresql
          port: 5432
          database: temporal_visibility
          user: postgres
          password: temporal123
          maxConns: 20
          maxConnLifetime: "1h"
  
postgresql:
    enabled: true
    auth:
      postgresPassword: temporal123
      database: temporal
    primary:
      persistence:
        enabled: true
        size: 10Gi

cassandra:
  enabled: false

elasticsearch:
  enabled: false

prometheus:
  enabled: false

grafana:
  enabled: false

web:
  enabled: true
  replicaCount: 1
  
admintools:
  enabled: true

schema:
  setup:
    enabled: true
  update:
    enabled: true

# Use reduced resource requests for demo
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi